
export const ACCOUNT_SIGNUP = 'ACCOUNT_SIGNUP';
export const ACCOUNT_SIGNUP_SUCCESS = 'ACCOUNT_SIGNUP_SUCCESS';
export const ACCOUNT_SIGNUP_FAILURE = 'ACCOUNT_SIGNUP_FAILURE';
export const ACCOUNT_SESSION = 'ACCOUNT_SESSION';
export const ACCOUNT_SESSION_SUCCESS = 'ACCOUNT_SESSION_SUCCESS';
export const ACCOUNT_SESSION_FAILURE = 'ACCOUNT_SESSION_FAILURE';

export const POST_LOADLIST = 'POST_LOADLIST';
export const POST_LOADLIST_SUCCESS = 'POST_LOADLIST_SUCCESS';
export const POST_LOADLIST_FAILURE = 'POST_LOADLIST_FAILURE';
export const POST_LOAD = 'POST_LOAD';
export const POST_LOAD_SUCCESS = 'POST_LOAD_SUCCESS';
export const POST_LOAD_FAILURE = 'POST_LOAD_FAILURE';
export const POST_WRITE = 'POST_WRITE';
export const POST_WRITE_SUCCESS = 'POST_WRITE_SUCCESS';
export const POST_WRITE_FAILURE = 'POST_WRITE_FAILURE';
export const POST_MODIFY = 'POST_MODIFY';
export const POST_MODIFY_SUCCESS = 'POST_MODIFY_SUCCESS';
export const POST_MODIFY_FAILURE = 'POST_MODIFY_FAILURE';
export const POST_REMOVE = 'POST_REMOVE';
export const POST_REMOVE_SUCCESS = 'POST_REMOVE_SUCCESS';
export const POST_REMOVE_FAILURE = 'POST_REMOVE_FAILURE';

export const SOCKET_POST_WRITE_SUCCESS = 'SOCKET_POST_WRITE_SUCCESS';
export const SOCKET_POST_MODIFY_SUCCESS = 'SOCKET_POST_MODIFY_SUCCESS';
export const SOCKET_POST_REMOVE_SUCCESS = 'SOCKET_POST_REMOVE_SUCCESS';
